// checksum 0xb4a version 0x7000b
/*
  This file was generated by the Html5 Application wizard of Qt Creator.
  Html5ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef HTML5APPLICATIONVIEWER_H
#define HTML5APPLICATIONVIEWER_H

#include <QFile>
#include <QFileSystemWatcher>
#include <QLatin1String>
#include <QStack>
#include <QStringList>
#include <QTextStream>
#include <QTimer>
#include <QUrl>
#include <QWidget>

#include "qextserialport.h"

class QGraphicsWebView;

class Html5ApplicationViewer : public QWidget
{
    Q_OBJECT

public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };

    explicit Html5ApplicationViewer(QWidget *parent = 0);
    virtual ~Html5ApplicationViewer();

    void loadFile(const QString &fileName);
    void loadUrl(const QUrl &url);

    // Note that this will only have an effect on Symbian and Fremantle.
    void setOrientation(ScreenOrientation orientation);

    void showExpanded();
    QStringList* parseDataFile();

    QGraphicsWebView *webView() const;
 public slots:
    void onDataAvailable();
    void onFileChange();
    void onCancelTimeout();

private:
    class Html5ApplicationViewerPrivate *m_d;
    QextSerialPort* port;
    QStack<QString> pageHistory;
    QFileSystemWatcher* fileWatcher;
    QFile* dataFile;
    QTextStream* dataText;
    QStringList* dataStrings;
    QString name;
    QString pin;
    QString enteredPin;
    QString language;
    QTimer cancelTimeout;
};

#endif // HTML5APPLICATIONVIEWER_H
